#!/usr/bin/env ruby

require 'foreman'
require 'foreman/env'

pushed = false
Foreman::Env.new('.env').entries do |key, value|
  if key == 'KANSO_DATABASE'
    system("kanso push #{value}")
    pushed = true
  end
end

if !pushed
  puts "Please set KANSO_DATABASE in your .env file."
end
